# [webservers]
# 172.31.85.40 ansible_ssh_user='ec2-user'
# 172.31.90.83 ansible_ssh_user='ec2-user'

[nfs]
172.31.6.219

[webservers]
172.31.85.40
172.31.90.83

[db]
172.31.13.186 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa

[lb]
172.31.13.93 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/id_rsa


[deployments:children]
nfs
webservers

[deployments:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3