---
- name: update web and nfs servers
  hosts: webservers, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the recent version
      yum:
        name: wireshark
        state: latest

- name: update LB server and db servers
  hosts: lb, db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
        state: latest

- name: Create directory, files and timezone in all servers
  hosts: webservers, nfs, lb, db
  become: yes
  tasks:

    - name: Create directory
      file: 
        path: /home/sample
        state: directory

    - name: Create files
      file: 
        path: /home/sample/ansible.txt
        state: touch

    - name: set timezones
      timezone: 
        name: Africa/Lagos
        